"""empty message

Revision ID: ef25316ca39b
Revises: 
Create Date: 2017-03-12 12:08:06.737283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef25316ca39b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('humidor',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('cigar',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('added_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('age_alert_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('custom_id', sa.String(), nullable=True),
    sa.Column('humidor_id', sa.String(), nullable=True),
    sa.Column('line', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('vitola', sa.String(), nullable=True),
    sa.Column('rest_alert_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['humidor_id'], ['humidor.uid'], name='cigar_humidor_uid_fkey'),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cigar')
    op.drop_table('user')
    op.drop_table('humidor')
    # ### end Alembic commands ###
